package com.example.ui.common

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "Train Tracker",
            "search_train" to "Search Train",
            "live_status" to "Live Train Status",
            "train_schedule" to "Train Schedule",
            "station_info" to "Station Info",
            "freight_trains" to "Freight Trains",
            "railway_news" to "Railway News",
            "weather" to "Weather",
            "namaz_timings" to "Namaz Timings",
            "favorites" to "Favorites",
            "profile" to "Profile",
            "settings" to "Settings",
            "search" to "Search",
            "source" to "Source Station",
            "destination" to "Destination Station",
            "departure" to "Departure",
            "arrival" to "Arrival",
            "duration" to "Duration",
            "delay" to "Delay",
            "current_station" to "Current Station",
            "next_station" to "Next Station",
            "previous_station" to "Previous Station",
            "eta" to "ETA",
            "etd" to "ETD",
            "running_days" to "Running Days",
            "last_updated" to "Last Updated",
            "distance_remaining" to "Distance Remaining",
            "facilities" to "Facilities",
            "nearby" to "Nearby",
            "today_arrivals" to "Today's Arrivals",
            "today_departures" to "Today's Departures",
            "delayed_trains" to "Delayed Trains",
            "cargo_type" to "Cargo Type",
            "current_pos" to "Current Position",
            "islamic_date" to "Islamic Date",
            "qibla" to "Qibla",
            "temperature" to "Temperature",
            "humidity" to "Humidity",
            "condition" to "Condition",
            "recent_searches" to "Recent Searches",
            "sign_up" to "Sign Up",
            "login" to "Log In",
            "logout" to "Log Out",
            "first_name" to "First Name",
            "last_name" to "Last Name",
            "email" to "Email Address",
            "phone" to "Phone Number",
            "password" to "Password",
            "confirm_password" to "Confirm Password",
            "terms" to "Terms & Conditions",
            "privacy" to "Privacy Policy",
            "agree_terms" to "I agree to the Terms & Privacy Policy",
            "submit" to "Submit",
            "verify_otp" to "Verify OTP",
            "enter_otp" to "Enter verification OTP sent via SMS/Email",
            "edit_profile" to "Edit Profile",
            "change_password" to "Change Password",
            "delete_account" to "Delete Account",
            "language" to "Language",
            "dark_mode" to "Dark Mode",
            "helpline" to "Helpline",
            "lost_found" to "Lost & Found",
            "railway_police" to "Railway Police",
            "ambulance" to "Ambulance",
            "fire_brigade" to "Fire Brigade",
            "empty_fav" to "No favorites added yet",
            "empty_searches" to "No search history",
            "clear_history" to "Clear History",
            "loading" to "Connecting to Railway Servers...",
            "home" to "Home",
            "notifications" to "Notifications",
            "emergency_helpline" to "Emergency Helplines",
            "app_customization" to "App Customizations",
            "about_legals" to "About & Legals",
            "version" to "Version",
            "copyright" to "Pakistan Railways IT Dept. © 2026",
            "select_route" to "Find Trains & Schedules",
            "recent_search_title" to "Recent Searches",
            "quick_services" to "Quick Services",
            "retry" to "Retry",
            "error_occurred" to "An error occurred",
            "no_internet" to "No Internet Connection"
        ),
        "ur" to mapOf(
            "app_name" to "ٹرین ٹریکر",
            "search_train" to "ٹرین تلاش کریں",
            "live_status" to "لائیو ٹرین اسٹیٹس",
            "train_schedule" to "ٹرین کا شیڈول",
            "station_info" to "اسٹیشن معلومات",
            "freight_trains" to "مال گاڑیاں",
            "railway_news" to "ریلوے کی خبریں",
            "weather" to "موسم",
            "namaz_timings" to "نماز کے اوقات",
            "favorites" to "پسندیدہ",
            "profile" to "پروفائل",
            "settings" to "ترتیبات",
            "search" to "تلاش کریں",
            "source" to "روانگی اسٹیشن",
            "destination" to "پہنچنے کا اسٹیشن",
            "departure" to "روانگی",
            "arrival" to "آمد",
            "duration" to "دورانیہ",
            "delay" to "تاخیر",
            "current_station" to "موجودہ اسٹیشن",
            "next_station" to "اگلا اسٹیشن",
            "previous_station" to "پچھلا اسٹیشن",
            "eta" to "توقع وقت آمد",
            "etd" to "توقع وقت روانگی",
            "running_days" to "چلنے کے دن",
            "last_updated" to "آخری اپ ڈیٹ",
            "distance_remaining" to "باقی فاصلہ",
            "facilities" to "سہولیات",
            "nearby" to "قریبی مقامات",
            "today_arrivals" to "آج کی آمد",
            "today_departures" to "آج کی روانگی",
            "delayed_trains" to "لیٹ ٹرینیں",
            "cargo_type" to "کارگو کی قسم",
            "current_pos" to "موجودہ پوزیشن",
            "islamic_date" to "اسلامی تاریخ",
            "qibla" to "قبلہ کی سمت",
            "temperature" to "درجہ حرارت",
            "humidity" to "نمی",
            "condition" to "موسمی صورتحال",
            "recent_searches" to "حالیہ تلاشیں",
            "sign_up" to "سائن اپ",
            "login" to "لاگ ان",
            "logout" to "لاگ آؤٹ",
            "first_name" to "پہلا نام",
            "last_name" to "آخری نام",
            "email" to "ای میل پتہ",
            "phone" to "فون نمبر",
            "password" to "پاس ورڈ",
            "confirm_password" to "پاس ورڈ کی تصدیق",
            "terms" to "شرائط و ضوابط",
            "privacy" to "رازداری کی پالیسی",
            "agree_terms" to "میں شرائط اور رازداری کی پالیسی سے متفق ہوں",
            "submit" to "جمع کروائیں",
            "verify_otp" to "او ٹی پی کی تصدیق",
            "enter_otp" to "ایس ایم ایس/ای میل کے ذریعے بھیجا گیا او ٹی پی درج کریں",
            "edit_profile" to "پروفائل ایڈٹ کریں",
            "change_password" to "پاس ورڈ تبدیل کریں",
            "delete_account" to "اکاؤنٹ حذف کریں",
            "language" to "زبان",
            "dark_mode" to "ڈارک موڈ",
            "helpline" to "ہیلپ لائن",
            "lost_found" to "گمشدہ اور پایا گیا",
            "railway_police" to "ریلوے پولیس",
            "ambulance" to "ایمبولینس",
            "fire_brigade" to "فائر بریگیڈ",
            "empty_fav" to "ابھی تک کوئی پسندیدہ شامل نہیں کیا گیا",
            "empty_searches" to "کوئی تلاش کی تاریخ نہیں ہے",
            "clear_history" to "ہسٹری صاف کریں",
            "loading" to "ریلوے سرورز سے منسلک ہو رہا ہے...",
            "home" to "ہوم",
            "notifications" to "اطلاعات",
            "emergency_helpline" to "ہنگامی ہیلپ لائنز",
            "app_customization" to "ایپ کی ترتیبات",
            "about_legals" to "معلومات و قانونی ضوابط",
            "version" to "ورژن",
            "copyright" to "پاکستان ریلوے آئی ٹی شعبہ © 2026",
            "select_route" to "ٹرینیں اور شیڈول تلاش کریں",
            "recent_search_title" to "حالیہ تلاشیں",
            "quick_services" to "فوری خدمات",
            "retry" to "دوبارہ کوشش کریں",
            "error_occurred" to "ایک غلطی پیش آگئی",
            "no_internet" to "انٹرنیٹ کنکشن موجود نہیں ہے"
        )
    )

    fun getText(key: String, lang: String): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
